sftp:
  config:
    remoteDirectory: /upload/in/statements/
    localDirectory: tmp/
    host: sftp
    user: tester
    password: password
    port: 22

spring:
  kafka:
    bootstrap-servers: http://broker:9092
    consumer:
      group-id: FIRST_GROUP

schema:
  registry:
    url: http://schema-registry:8081

s3:
  config:
    url: http://localstack:4566
    region: south-east-1
    access-key-id: test
    secret-key-id: test

application:
  config:
    reader:
      integration-code: ECS-BANK
      process: STATEMENTS
      validation-required: true
      topic: Transformation1
